artifact_uri: file://D:\MyFiles\Work\Personal\Job Interview Related Tasks\mini-ment\stores\model/307872308376253003/f2f2d20eba2344eb8a2ca9d1aa380ec7/artifacts
end_time: 1690129261525
entry_point_name: ''
experiment_id: '307872308376253003'
lifecycle_stage: active
run_id: f2f2d20eba2344eb8a2ca9d1aa380ec7
run_name: logistic_regression_run
run_uuid: f2f2d20eba2344eb8a2ca9d1aa380ec7
source_name: ''
source_type: 4
source_version: ''
start_time: 1690127726209
status: 3
tags: []
user_id: ahmad
