artifact_uri: file://D:\MyFiles\Work\Personal\Job Interview Related Tasks\mini-ment\stores\model/429732939423570924/7c2c34bccda3416bb1ac44ad181b3a6d/artifacts
end_time: 1690301587133
entry_point_name: ''
experiment_id: '429732939423570924'
lifecycle_stage: active
run_id: 7c2c34bccda3416bb1ac44ad181b3a6d
run_name: '5'
run_uuid: 7c2c34bccda3416bb1ac44ad181b3a6d
source_name: ''
source_type: 4
source_version: ''
start_time: 1690301585212
status: 3
tags: []
user_id: ahmad
