artifact_location: file://D:\MyFiles\Work\Personal\Job Interview Related Tasks\mini-ment\stores\model/429732939423570924
creation_time: 1690300710040
experiment_id: '429732939423570924'
last_update_time: 1690300710040
lifecycle_stage: active
name: logistic_regression_study
