artifact_uri: file://D:\MyFiles\Work\Personal\Job Interview Related Tasks\mini-ment\stores\model/307872308376253003/628cd5a4e5c7498d8a7f4b67bb7a907a/artifacts
end_time: 1690303230726
entry_point_name: ''
experiment_id: '307872308376253003'
lifecycle_stage: active
run_id: 628cd5a4e5c7498d8a7f4b67bb7a907a
run_name: logistic_regression_run
run_uuid: 628cd5a4e5c7498d8a7f4b67bb7a907a
source_name: ''
source_type: 4
source_version: ''
start_time: 1690303143553
status: 3
tags: []
user_id: ahmad
