artifact_location: file://D:\MyFiles\Work\Personal\Job Interview Related Tasks\mini-ment\stores\model/307872308376253003
creation_time: 1690127725665
experiment_id: '307872308376253003'
last_update_time: 1690127725665
lifecycle_stage: active
name: logistic_regression_exp
